### ISSUE TITLE
move files anbd settings 

### ISSUE THREAD

**Issue by rayansdsd** [edissyum/opencapture#1349]
hey, 
we  were working an open capture and we created a supplier a client masks ...ext in device and we want to move them to another device we tried to find the folders and files of these settings to copy them to the other device  but we couldn't find these files and we want to know is to possible thank you for answering us

**Comment by nathan30** [comment]
If I understand well you want to transfer positions masks settings from one Open-Capture installation to another ?

If yes, you need to retrieve lines in the table `positions_masks` using pg_dump (I let your search to get the full command to retrieve one table only) and then pg_restore on your new database. The files of positions masks are located (by default) here : `/var/docservers/opencapture/CUSTOM_NAMEverifier/positions_masks`

**Comment by rayansdsd** [comment]
i want to transfere evrything from an installation on devide to another device because we were in vma and now we cahnged to ubuntu and it's important for us to move everything

**Comment by rayansdsd** [comment]
![Capture d’écran du 2024-03-18 14-57-15](https://github.com/edissyum/opencapture/assets/113535788/7ecfbedf-62e9-4d7b-9755-b4b4493d0cc2)
 i want to move all this settings i want o move everything how i could do that

**Comment by nathan30** [comment]
We don't have procedure to migrate instance to another. You can make a fresh installation on your new servers and then manually dump and restore the databases and copy all the docservers to your new installation

But you have to know that Ubuntu isn't fully supported and install could fail because of packages name and/or version

**Comment by rayansdsd** [comment]
how i could copy all the docservers to my new installation

**Comment by rayansdsd** [comment]
can you answer me please

**Comment by nathan30** [comment]
I already told you how to do that. We can't provide further help here. Do not hesitate to contact Edissyum Consulting (04 90 40 91 86) and ask for Cédric Rouire to have more support

Regards
