### ISSUE TITLE
position mask

### ISSUE THREAD

**Issue by rayansdsd** [edissyum/opencapture#1350]
the second problem which i have is that i have created position mask with 3  data:
date which is already in the formulair
and there s the name of the client and customer but when i do the process it doesn t get these data except the date

**Comment by nathan30** [comment]
Could you send me an example of your doc ? I need to reproduce the issue

**Comment by rayansdsd** [comment]
I have created personal form with the date and a client and supplier as you see
![Capture d’écran du 2024-03-20 10-55-36](https://github.com/edissyum/opencapture/assets/113535788/fec02fb0-0de5-490c-8256-62c64ffa153e)
that i created a position mask for each data 
![Capture d’écran du 2024-03-20 10-55-56](https://github.com/edissyum/opencapture/assets/113535788/d44728ca-1237-47b7-a92b-a22c08ae066c)
then i droped this document 
![Capture d’écran du 2024-03-20 11-10-11](https://github.com/edissyum/opencapture/assets/113535788/1a80538e-5e6f-4d46-85e4-fb31deaf6ddb)
but when i go to validate there's no data recognized, in the beginning it recognized the data but now even the date can't recognized. i don't now why the position mask it's not considered.
N.B: when i go to validate and i give it the position manually as you see it recognized the data.
![Capture d’écran du 2024-03-20 11-14-07](https://github.com/edissyum/opencapture/assets/113535788/e69c5862-34d7-4eeb-90a8-649d61cf47c2)
thyank you for helping me

**Comment by rayansdsd** [comment]
i tried with different document but it doesn't recognized the Data i don't what I'm missing

**Comment by rayansdsd** [comment]
can answer me today please , thank for your understanding

**Comment by nathan30** [comment]
The issue is normal. A position mask is linked to a third party account (Comfert in your example). If this one is not found, the positions masks will not be use

**Comment by rayansdsd** [comment]
when you say it s not found do you mean on the document which i am checking?
sorry but i can t make the product work i have tried everything, i watched the tutorials tho.

**Comment by rayansdsd** [comment]
okay but what if on my document there's no supplier information how i could extract data from the document. for exemple i have documents which look like this one below 
![Capture d’écran du 2024-03-20 10-55-56](https://github.com/edissyum/opencapture/assets/113535788/cf0f9641-ab51-4095-9d02-effa28997985)
how i could extract data as name of the client and the suplier and date in this case

**Comment by rayansdsd** [comment]
well i want to notify that i tried to name the supllier ETAT DES RECEPTIONS CLIENTS wich is a phrase in all the document so he reconized the supplier to use the mast but it doesn t use it again

**Comment by nathan30** [comment]
Without supplier information, it's more difficult. You have to create custom fields with REGEX type and spend some time on it to made a powerful REGEX

You'll find it under ''Paramètres généraux"

**Comment by nathan30** [comment]
The name isn't use to find supplier. Only vat number, siret, siren, iban. But we made a verification on this data, so you can't fake it right now
