### ISSUE TITLE
https://open-capture.com down

### ISSUE THREAD

**Issue by bzg** [edissyum/opencapture#1434]
The website (wordpress?) seems down at the moment.

**Comment by nathan30** [comment]
Hi,

I just try and it's okay. Do you have an error message ?

![image](https://github.com/edissyum/opencapture/assets/7926051/2eab4a85-9d1d-40f1-93c7-e12566f645e9)

**Comment by bzg** [comment]
![Uploading 2024-06-20-100802_1680x1050_scrot.png…]()

**Comment by nathan30** [comment]
I can't see your picture :/

**Comment by bzg** [comment]
Fixed!

**Comment by nathan30** [comment]
Could you try again ? We just restart the server, it should be ok

**Comment by bzg** [comment]
It works, thanks!
