### ISSUE TITLE
How to start AI

### ISSUE THREAD

**Issue by martin-korf** [edissyum/opencapture#886]
Hello everyone,
We just installed version 2.9.0 of Open-Capture. Is there any way of how to start the AI in it? I don't have any opinion to upload documents, so how to do it? I tried to search it in the GitBook, but the Franche language is not so familiar to me.

![image](https://github.com/edissyum/opencapture/assets/17021120/b3c11240-49f5-4537-ac7a-b5d106b8fbd2)

Thanks for help

**Comment by nathan30** [comment]
Hi,

The document isn't ready yet in English, sorry for that. Moreover, we didn't have the time yet to write AI documentation

To train your model you have to: 

- Locate your docservers folder (by default `/var/docservers/opencapture/CUSTOM_ID/`)
- Choose if you want an AI model for Verifier or Splitter module (regarding your name, it's probably verifier)
- In the `/var/docservers/opencapture/CUSTOM_ID/verifier/ai/train_data/` folder create subfolders with the name you want
- In each folder you just created, you can now add PDF files
- Then in the UI you'll see your folders and you can start training

Btw, if you see any errors in translation, do not hesitate to create pull request :)

**Comment by martin-korf** [comment]
Hi @nathan30 ,
thanks for your message :) the step manuals was usefully and I can now train the AI :)

I noticed two issued with translation - one is with AI directly:
![image](https://github.com/edissyum/opencapture/assets/17021120/d286c785-b152-44ba-aec6-c91b0ba7e3af)

and the second is in the General>Configurations> The description is not translated :)  
![image](https://github.com/edissyum/opencapture/assets/17021120/c8b5ad88-f095-4102-b2cd-a71549e92263)


Should I create a separated bug report for both of them? :)

Best Regards
Martin

**Comment by nathan30** [comment]
Thanks for your report. I'll fix the first translation in the next big update coming v3.0.0

The main issue about the second translation error is that it's related to the data_fr.sql file (the default database data in the application). For now, we didn't have the time and funding to create a data_en.sql
